version: "3.5"
services:
  postgresql:
    restart: always
    image: postgres:11
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        # We want this service to be deployed on a node with a worker role
        constraints:
          - node.role == worker
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  sonar:
    restart: always
    image: daabramov/sonarfor1c:9.9-community
    ports:
      - "32772:9000"
    depends_on:
      - postgresql
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        # We want this service to be deployed on a node with a worker role
        constraints:
          - node.role == worker
    environment:
      - SONAR_WEB_JAVAOPTS=-server -Xms1g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError
      - SONAR_CE_JAVAOPTS=-Xms4g -Xmx4g -XX:+HeapDumpOnOutOfMemoryError
      - SONAR_SEARCH_JAVAOPTS=-Xms2g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_conf:
    driver_opts:
      type: nfs
      o: addr=192.168.1.141,nolock,soft,rw
      device: ":/mnt/volumes/sonarqube/conf"
  sonarqube_data:
    driver_opts:
      type: nfs
      o: addr=192.168.1.141,nolock,soft,rw
      device: ":/mnt/volumes/sonarqube/data"
  sonarqube_extensions:
    driver_opts:
      type: nfs
      o: addr=192.168.1.141,nolock,soft,rw
      device: ":/mnt/volumes/sonarqube/extensions"
  postgresql:
    driver_opts:
      type: nfs
      o: addr=192.168.1.141,nolock,soft,rw
      device: ":/mnt/volumes/sonarqube/postgresql"
  postgresql_data:
    driver_opts:
      type: nfs
      o: addr=192.168.1.141,nolock,soft,rw
      device: ":/mnt/volumes/sonarqube/postgresql_data"
