version: "3.1"

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry_data_test:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

volumes:
  registry_data_test:
    driver_opts:
      type: nfs
      o: addr=192.168.1.141,nolock,soft,rw
      device: ":/mnt/volumes/registry/registry_data"
